# Generated by Django 5.2 on 2025-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_incident_incidentupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='related_services',
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_services',
            field=models.ManyToManyField(related_name='incidents', to='services.service'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20),
        ),
    ]
